blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blogger/<int:pk>', views.BlogListbyAuthorView.as_view(), name='blogs-by-author'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blog/<int:pk>/comment/', views.BlogCommentCreate.as_view(), name='blog_comment'),
]

djangodiyblog/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include

urlpatterns += [
    path('blog/', include('blog.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class BlogAuthor(models.Model):
    """Model represnting a Blog author called bloggers"""
    bio = models.TextField(max_length=400, help_text = 'Enter Bio details')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ["user","bio"]

    def get_absolute_url(self):
        """ Returns the url to access a particular blog-author instance."""
        return reverse('blogs-by-author', args=[str(self.id)])
    
    def __str__(self):
        """String for represnting the Model Blog."""
        return self.user.username

class Blog(models.Model):
    """Model representing a Blog"""
    name = models.CharField(max_length=200, help_text='Enter a blog name(e.g. Science Fiction)')
    description = models.TextField(max_length=2000, help_text='Enter a blog description(e.g. Science Fiction)')
    author = models.CharField(max_length=200, help_text='Enter a blog description(e.g. Science Fiction)')
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
    post_date = models.DateField(default=date.today)

    class Meta:
        ordering = ["-post_date"]

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])

class BlogComment(models.Model):
    """Model represnting the blof comment"""
    description = models.TextField(max_length = 4000, help_text='Enter the blog comment')
    post_date = models.DateField(default=date.today)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    Blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        len_title = 75
        if len(self.description)>len_title:
            titlestring=self.description[:len_title] + '...'
        else:
            titlestring=self.description
        return titlestring

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Blog, BlogAuthor, BlogComment
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse
import pdb; 
pdb.set_trace()
# Create your views here.

def index(request):
    """
    View function for home page of site.
    """
    # Render the HTML template index.html
    return render(
        request,
        'index.html',
    )

class BlogListView(generic.ListView):
    """
    Generic class-based view for a list of all blogs.
    """
    model = Blog
    paginate_by = 5
    template = 'blog/blog_list.html'

class BlogDetailView(generic.DetailView):
    """
    Generic class-based detail view for a blog.
    """
    model = Blog

class BloggerListView(generic.ListView):
    """
    Generic class-based view for a list of bloggers.
    """
    model = BlogAuthor
    paginate_by = 5

class BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a blog comment. Requires login. 
    """
    model = BlogComment
    fields = ['description',]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blog'] = get_object_or_404(Blog, pk = self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.author = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog=get_object_or_404(Blog, pk = self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self): 
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'],})

class BlogListbyAuthorView(generic.ListView):
    """
    Generic class-based view for a list of blogs posted by a particular BlogAuthor.
    """
    model = Blog
    paginate_by = 5
    template_name ='blog/blog_list_by_author.html'
    
    def get_queryset(self):
        """
        Return list of Blog objects created by BlogAuthor (author id specified in URL)
        """
        id = self.kwargs['pk']
        target_author=get_object_or_404(BlogAuthor, pk = id)
        return Blog.objects.filter(author=target_author)
        
    def get_context_data(self, **kwargs):
        """
        Add BlogAuthor to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blogger'] = get_object_or_404(BlogAuthor, pk = self.kwargs['pk'])
        return context

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Django DIY Blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  <ul class="sidebar-nav">
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'blogs' %}">All blogs</a></li>
    <li><a href="{% url 'bloggers' %}">All bloggers</a></li>
  </ul>
  
  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 
  </ul>
 
  {% endblock %}
  </div>
  <div class="col-sm-10 ">
  {% block content %}{% endblock %}
  
  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %} 
  
  </div>
</div>

</div>
</body>
</html>

blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>{{ blog.name }}</h1>
<p><strong>Post date</strong> {{ blog.post_date }}</p>
<p><strong>Author:</strong> <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a></p>
<p><strong>Description:</strong></p>
<p style="white-space:pre-wrap;">{{ blog.description }}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Comments</h4>

{% for comment in blog.blogcomment_set.all %}
<hr>
<p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  <a href="{% url 'blog_comment' blog.id %}">Add a new comment</a></p>
{% else %}
  <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
{% endif %} 


</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>{{ blog.name }}</h1>
<p><strong>Post date</strong> {{ blog.post_date }}</p>
<p><strong>Author:</strong> <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a></p>
<p><strong>Description:</strong></p>
<p style="white-space:pre-wrap;">{{ blog.description }}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Comments</h4>

{% for comment in blog.blogcomment_set.all %}
<hr>
<p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  <a href="{% url 'blog_comment' blog.id %}">Add a new comment</a></p>
{% else %}
  <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
{% endif %} 


</div>
{% endblock %}

blog/templates/blog/blog_list_by_author.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger: {{blogger}}</h1>
    
    <h3>Bio</h3>
    
    <p>{{blogger.bio}}</p>
    
    

    {% if blog_list %}
    <h3>Blogs list</h3>
    <ul>

      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}})</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>This blogger hasn't posted anything yet.</p>
    {% endif %}       
{% endblock %}

blog/templates/blog/blogauthor_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All bloggers</h1>

    {% if blogauthor_list %}
    <ul>

      {% for author in blogauthor_list %}
      <li>
        <a href="{% url 'blogs-by-author' author.pk %}">{{ author }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no bloggers yet.</p>
    {% endif %}       
{% endblock %}

blog/templates/blog/blogcomment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{blog.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blog/templates/blogs/blog_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>{{ blog.name }}</h1>
<p><strong>Post date</strong> {{ blog.post_date }}</p>
<p><strong>Author:</strong> <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a></p>
<p><strong>Description:</strong></p>
<p style="white-space:pre-wrap;">{{ blog.description }}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Comments</h4>

{% for comment in blog.blogcomment_set.all %}
<hr>
<p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  <a href="{% url 'blog_comment' blog.id %}">Add a new comment</a></p>
{% else %}
  <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
{% endif %} 


</div>
{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>DIY Blog Home</h1>

<p>Welcome to <em>DIY Blog</em>, a very basic Django blogging website developed as an <a href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/django_assessment_blog">assessment task</a> for the Django learning module on the Mozilla Developer Network.</p>



<h2>UML Models</h2>
<p>An UML diagram of the site's Django model structure is shown below. </p>

<div>
{% load static %}
<img src="{% static "images/diy_django_mini_blog_models.png" %}" alt="My image" style="width:555px;height:540px;"/>
</div>  

{% endblock %}